const OrderStatus = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
    ASSIGNED_TO_DELIVERER: "ASSIGNED_TO_DELIVERER",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
    DELIVERY_CONFIRMED: "DELIVERY_CONFIRMED",
    FAILED: "FAILED",
    CANCELED: "CANCELED",
};
  
module.exports = OrderStatus;